# ~/secdevops-a3/nextcloud/compose.yaml
name: nextcloud-stack
services:
  db:
    image: postgres:16-alpine
    container_name: nc-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ncuser
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: nextcloud
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 3s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: ncuser
      POSTGRES_PASSWORD: supersecret
      NEXTCLOUD_TRUSTED_DOMAINS: "localhost 127.0.0.1"
    expose:
      - "80"     # visible to Portainer/others on network only
    ports:
      - "8080:80" # publish to host for browser access
    volumes:
      - nc_data:/var/www/html
    security_opt:
      - no-new-privileges:true

volumes:
  db_data:
  nc_data:

